pivotes:
  - id: apertura_cortes
    nombre: Apertura de las Cortes de Cádiz
    jornada: 20
    mutaciones:
      - tipo: acto_narrativo
        valor: 2
      - tipo: estado_global
        valor: CrisisAbierta
      - tipo: tema_caliente
        valor: constitucion_1812

  - id: constitucion_1812
    nombre: Promulgación de la Constitución de 1812
    jornada: 40
    mutaciones:
      - tipo: acto_narrativo
        valor: 3
      - tipo: estado_global
        valor: CelebracionPublica
      - tipo: tema_caliente
        valor: libertad_prensa

  - id: invasion_francesa
    nombre: Invasión Francesa de Andalucía
    jornada: 60
    mutaciones:
      - tipo: acto_narrativo
        valor: 4
      - tipo: estado_global
        valor: CrisisAbierta
      - tipo: tema_caliente
        valor: defensa_nacional