---
config_facciones:
  - id: "liberales_progresistas"
    nombre: "Liberales Progresistas"
    tipo: "politica"
    capacidades_presion: ["prensa", "oratoria"]
    fuerza_inicial: 2
    cohesion_inicial: 2
    necesidad_jugador_inicial: 1
  - id: "consulado"
    nombre: "Consulado de Cádiz"
    tipo: "economica"
    capacidades_presion: ["credito", "redes_comerciales"]
    fuerza_inicial: 4
    cohesion_inicial: 3
    necesidad_jugador_inicial: 3
  - id: "serviles"
    nombre: "Absolutistas (Serviles)"
    tipo: "politica"
    capacidades_presion: ["ejercito", "iglesia"]
    fuerza_inicial: 3
    cohesion_inicial: 2
    necesidad_jugador_inicial: 1
